import type { Metadata } from "next";
import { Header } from "@/shared/components/shared/header";
import React from "react";

export const metadata: Metadata = {
  title: "Next pizza | Главная",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main className="min-h-screen">
        {children}
        {modal}
      </main>
    </>
  );
}
