import React from "react";
import { Metadata } from "next";
import { Header } from "@/shared/components/shared";

export const metadata: Metadata = {
  title: "Next pizza | Checkout",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Header
        className="border-gray-200"
        hasSearch={false}
        hasCartButton={false}
      />
      {children}
    </main>
  );
}
